### ISSUE TITLE
Can you find this kind of hole? And show the edge fill

### ISSUE THREAD

**Issue by WREQI** [sebadorn/WebGL-Hole-Filling#3]
![image](https://user-images.githubusercontent.com/35467304/104988167-5e3ff500-5a52-11eb-9b17-9ed3f981b0fd.png)
Can you find this kind of hole? And show the edge fill

**Comment by sebadorn** [comment]
Seems like these holes go through the 3D model, but do not break the surface. The inside of the model is still air-tight. My application cannot detect these holes.
