### ISSUE TITLE
testing on voxelized mesh

### ISSUE THREAD

**Issue by antonymarion** [sebadorn/WebGL-Hole-Filling#4]
![image](https://user-images.githubusercontent.com/8767496/105497899-c5aeac80-5cbf-11eb-96d3-ae88f3eba5b4.png)

Hi,

Does it work on this ?

**Comment by sebadorn** [comment]
No. I assume the voxelized model consists of a lot of cubes. The cubes next to each other look like the model, but for the application it is just a lot of cubes and the cubes themselves have no holes in them.
